version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_NAME=api
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - POSTGRES_URL=postgres://postgres:postgres@postgres:5432/bankdb?sslmode=disable
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=bankdb
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - postgres
      - mongo
      - rabbitmq
    restart: on-failure

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_NAME=worker
    environment:
      - POSTGRES_URL=postgres://postgres:postgres@postgres:5432/bankdb?sslmode=disable
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=bankdb
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - postgres
      - mongo
      - rabbitmq
    restart: on-failure

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bankdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  mongo_data:
  rabbitmq_data: