api:
  port: "8080"

postgres:
  host: "localhost"
  port: 5432
  user: "bank_user"
  password: "bank_password"
  database: "bank_db"

mongo:
  host: "localhost"
  port: 27017
  user: "mongo_user"
  password: "mongo_password"
  database: "bank_db"

rabbitmq:
  host: "localhost"
  port: 5672
  user: "guest" #  Default RabbitMQ user
  password: "guest" #  Default RabbitMQ password
  account_queue: "account.create"
  transaction_queue: "transaction.process"